version: "3"

services: 
    db:
      image: postgres
      container_name: postgres
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: signupapp
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      restart: always
      ports:
        - '5432:5432'
    
    adminer:
      image: adminer
      container_name: adminer
      restart: always
      ports:
        - 8080:8080
      environment:
        ADMINER_DEFAULT_SERVER: postgres

    signupapi:
      build: ./backend/
      container_name: signupapi
      command: sh ./docker-entrypoint.sh
      restart: always
      ports:
        - 4000:4000
      depends_on:
        - db
      environment:
        POSTGRES_USERNAME: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: postgres
        POSTGRES_DATABASE: signupapp
            # POSTGRES_PORT: 5432
            # # DATABASE_URL: "postgres://postgres:postgres@localhost/signupapp"
            # NODE_ENV: local